name: Next.js App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  all-cli-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  #checkout code
      - uses: actions/setup-node@v4 #setup Node.js
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Run Prettier
        run: npx prettier --write .

      - name: Type check
        run: npx tsc --noEmit

      - name: Run tests
        run: npm test

      - name: Build app
        run: npm run build

      - name: Check if .next directory exists
        run: |
          echo "Root:"
          ls -la
          echo ".next folder contents:"
          ls -la .next || echo ".next not found!"

      - name: Check build output
        run: ls -la && ls -la .next

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: .next
#  e2e:
#    name: Run Playwright E2E Tests
#    needs: all-cli-checks
#    runs-on: ubuntu-latest
#    timeout-minutes: 60
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Setup Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: 18
#          cache: 'npm'
#
#      - name: Install dependencies
#        run: npm ci
#
#      - name: Run Playwright Tests
#        run: npx playwright test

  deploy:
    name: Deploy to Vercel (Production)
    needs: all-cli-checks
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && success()

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - uses: actions/download-artifact@v4
        with:
          name: nextjs-build
          path: .next
      - name: Vercel Deployment
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          zeit-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          prod: true
